-- CreateTable
CREATE TABLE "Submission" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nome" TEXT NOT NULL,
    "cognome" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "telefono" TEXT,
    "eta" INTEGER,
    "peso" REAL,
    "altezza" REAL,
    "citta" TEXT,
    "privacyConsent" BOOLEAN NOT NULL DEFAULT true,
    "locusAnswers" TEXT NOT NULL,
    "eventiSaluteAnswers" TEXT NOT NULL,
    "medicineAlternativeAnswers" TEXT NOT NULL,
    "leadershipAnswers" TEXT NOT NULL,
    "selfAssessmentAnswers" TEXT NOT NULL,
    "lifestyleAnswers" TEXT NOT NULL,
    "locusScore" REAL NOT NULL,
    "locusNormalized" REAL NOT NULL,
    "eventiSaluteScore" REAL NOT NULL,
    "eventiSaluteNormalized" REAL NOT NULL,
    "medicineAlternativeScore" REAL NOT NULL,
    "medicineAlternativeNormalized" REAL NOT NULL,
    "leadershipScore" REAL NOT NULL,
    "leadershipNormalized" REAL NOT NULL,
    "selfAssessmentAverage" REAL NOT NULL,
    "locusInterpretation" TEXT NOT NULL,
    "eventiInterpretation" TEXT NOT NULL,
    "medicineInterpretation" TEXT NOT NULL,
    "leadershipInterpretation" TEXT NOT NULL,
    "emailSent" BOOLEAN NOT NULL DEFAULT false,
    "adminViewed" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT
);
